import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// import profilePic from "../public/me.png";
import img1 from "../public/images/1.jpg";
import img2 from "../public/images/2.jpg";
import img3 from "../public/images/3.jpg";
import img4 from "../public/images/4.jpg";
import logo from "../public/logo.png";
export default function Home(res) {
  const data = res.res.statewise[0];
  console.log(res);
  return (
    <div className={styles.container}>
      <Head>
        <title>Covid 19 Tracker-IN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <center>
          <h3> 🔴 LIVE COVID-19 Tracker</h3>
          <h2>COVID-19 CORONAVIRUS TRACKER FOR INDIA</h2>
        </center>

        <div className="cards-list">
          <div className="card 1">
            <center>
              <h1>Country</h1>
            </center>

            <div className="card_image">
              <Image
                src={img1}
                id="imgcs"
                objectFit="responsive"
                placeholder="blur"
                objectFit="fill"
                height={400}
                width={400}
              />
              {/* <img loading="lazy" src="images/1.jpg" alt="img1" /> */}
            </div>
            <div className="card_title title-white">
              <p>INDIA</p>
            </div>
          </div>

          <div className="card 2">
            <center>
              <h1>
                <b>{data.recovered}</b>
              </h1>
            </center>
            <div className="card_image">
              <Image
                id="imgcs"
                src="https://media.giphy.com/media/10SvWCbt1ytWCc/giphy.gif"
                objectFit="fill"
                height={400}
                width={400}
                placeholder="blurDataURL"
              />
              {/* <img
              loading="lazy"
              src="https://media.giphy.com/media/10SvWCbt1ytWCc/giphy.gif"
              alt="img"
            /> */}
            </div>
            <div className="card_title title-green">
              <p>Total Recovered</p>
            </div>
          </div>

          <div className="card 3">
            <div className="card_image">
              <center>
                <h1>
                  <b>{data.confirmed}</b>
                </h1>
              </center>
              <Image
                id="imgcs"
                src={img2}
                objectFit="fill"
                height={400}
                width={400}
                placeholder="blur"
              />
            </div>
            <div className="card_title title-green">
              <p>Total Confirmed</p>
            </div>
          </div>

          <div className="card 4">
            <div className="card_image">
              <center>
                <h1>
                  <b>{data.deaths}</b>
                </h1>
              </center>
              <Image
                id="imgcs"
                src="https://media.giphy.com/media/LwIyvaNcnzsD6/giphy.gif"
                objectFit="fill"
                height={400}
                width={400}
                placeholder="blurDataURL"
              />
            </div>

            <div className="card_title title-red">
              <p>TOTAL DEATHS</p>
            </div>
          </div>
          <div className="card 5">
            <div className="card_image">
              <center>
                <h1>
                  <b>{data.active}</b>
                </h1>
              </center>
              <Image
                id="imgcs"
                src={img3}
                objectFit="fill"
                height={400}
                width={400}
                placeholder="blur"
              />
            </div>
            <div className="card_title title-red">
              <p>CURRENT ACTIVE CASE</p>
            </div>
          </div>
          <div className="card 6">
            <div className="card_image">
              <center>
                <h1>
                  <b>{data.lastupdatedtime}</b>
                </h1>
              </center>
              <Image
                id="imgcs"
                src={img4}
                objectFit="fill"
                height={400}
                width={400}
                placeholder="blur"
              />
            </div>
            <div className="card_title title-white">
              <p>
                <b>LAST UPDATE</b>
              </p>
              <h3>Updating</h3>
            </div>
          </div>
        </div>

        <footer className={styles.footer}>
          <a
            href="https://profile-sdedj.vercel.app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Developed By{""}
            <span className={styles.logo}>
              <Image src={logo} alt="logo" width={32} height={26} />
            </span>
          </a>
        </footer>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://api.covid19india.org/data.json").then(
    (res) => res.json()
  );
  return {
    props: {
      res,
    },
    revalidate: 6,
  };
}
